src/Entity/DaneKlienta.php
<?php

namespace App\Entity;
use App\Repository\DaneKlientaRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DaneKlientaRepository::class)]
class DaneKlienta
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $Imie;

    #[ORM\Column(type: 'string', length: 255)]
    private $Nazwisko;

    #[ORM\Column(type: 'string', length: 255)]
    private $Miasto;

    #[ORM\Column(type: 'string', length: 255)]
    private $KodPocztowy;

    #[ORM\Column(type: 'string', length: 255)]
    private $Adres;

    #[ORM\Column(type: 'integer', nullable:true)]
    private $NumerZamowienia;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getImie(): ?string
    {
        return $this->Imie;
    }

    public function setImie(string $Imie): self
    {
        $this->Imie = $Imie;

        return $this;
    }

    public function getNazwisko(): ?string
    {
        return $this->Nazwisko;
    }

    public function setNazwisko(string $Nazwisko): self
    {
        $this->Nazwisko = $Nazwisko;

        return $this;
    }

    public function getMiasto(): ?string
    {
        return $this->Miasto;
    }

    public function setMiasto(string $Miasto): self
    {
        $this->Miasto = $Miasto;

        return $this;
    }

    public function getKodPocztowy(): ?string
    {
        return $this->KodPocztowy;
    }

    public function setKodPocztowy(string $KodPocztowy): self
    {
        $this->KodPocztowy = $KodPocztowy;

        return $this;
    }

    public function getAdres(): ?string
    {
        return $this->Adres;
    }

    public function setAdres(string $Adres): self
    {
        $this->Adres = $Adres;

        return $this;
    }

    public function getNumerZamowienia(): ?int
    {
        return $this->NumerZamowienia;
    }

    public function setNumerZamowienia(?int $NumerZamowienia): self
    {
        $this->NumerZamowienia = $NumerZamowienia;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>



        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>


   
        {% block body %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
         <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.6/dist/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>{% endblock %}
    </body>
</html>

templates/kontakt.html.twig
{% extends 'base.html.twig' %}
{% block title %}Kontakt{% endblock %}
{% block body %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" aria-label="Fifth navbar example">
        <div class="container-fluid">
            <a href="{{ path('app_crud_index') }}">
                <img src="https://kacperglowacki1.000webhostapp.com/usmieszek.png" alt="logo" width="50" height="50">
            </a>
            <button class="navbar-toggler ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon ms-auto"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarsExample05">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                    <li class="nav-item"><a href="{{ path('app_crud_index') }}" class="nav-link" aria-current="page">HOME</a></li>


                    <li class="nav-item"><a href="{{ path('app_ostronie') }}" class="nav-link">O STRONIE</a></li>


                    <li class="nav-item"><a href="{{ path('app_kontakt') }}" class="nav-link  active">KONTAKT</a></li>

                </ul></div>
            <div class="collapse navbar-collapse" id="navbarsExample05">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item"><a class="btn btn-light" href="{{ path('app_login') }}" role="button">Zaloguj sie</a>
                    </li>
                    <li class="nav-item"><a class="btn btn-light" href="{{ path('app_logout') }}" role="button">Wyloguj sie</a>
                    </li>
                </ul></div>


        </div>

    </nav>
    <h3>Wszystkie problemy ze stroną proszę zgłaszać tutaj: <br>
     email: kacperjcb@gmail.com
        <h3>

{% endblock %}

templates/ostronie.html.twig
{% extends 'base.html.twig' %}
{% block title %}O stronie{% endblock %}
{% block body %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" aria-label="Fifth navbar example">
        <div class="container-fluid">
            <a href="{{ path('app_crud_index') }}">
                <img src="https://kacperglowacki1.000webhostapp.com/usmieszek.png" alt="logo" width="50" height="50">
            </a>
            <button class="navbar-toggler ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon ms-auto"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarsExample05">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                    <li class="nav-item"><a href="{{ path('app_crud_index') }}" class="nav-link" aria-current="page">HOME</a></li>


                    <li class="nav-item"><a href="{{ path('app_ostronie') }}" class="nav-link active">O STRONIE</a></li>


                    <li class="nav-item"><a href="{{ path('app_kontakt') }}" class="nav-link">KONTAKT</a></li>

                </ul></div>
            <div class="collapse navbar-collapse" id="navbarsExample05">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item"><a class="btn btn-light" href="{{ path('app_login') }}" role="button">Zaloguj sie</a>
                    </li>
                    <li class="nav-item"><a class="btn btn-light" href="{{ path('app_logout') }}" role="button">Wyloguj sie</a>
                    </li>
                </ul></div>

            </li>

            </ul>

        </div>
    </nav>
    <h3>Strona służy do składania zamówień wewnątrz firmy na różne produkty<br>

        <h3>
{% endblock %}

templates/polaczonedane.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    {% if (is_granted('ROLE_ADMIN'))%}
    <table class="table table-striped table-dark">
        <thead>
        <tr>
            <th>ID</th>
            <th>Imie</th>
            <th>Nazwisko</th>
            <th>Miasto</th>
            <th>Kod_pocztowy</th>
            <th>Adres</th>
            <th>Nazwa_produktu</th>
            <th>Opis_produktu</th>
        </tr>
        </thead>
        <tbody>

{% for crud in polaczone %}






    <tr>
        <td>{{crud.id }}</td>
        <td>{{crud.imie }}</td>
        <td> {{crud.nazwisko}}</td>
        <td> {{crud.miasto}}</td>
        <td> {{crud.kod_pocztowy}}</td>
        <td> {{crud.adres}}</td>
        <td> {{crud.nazwa_produktu}}</td>
        <td> {{crud.opis_produktu}}</td>
    </tr>
{% else %}
    <tr>
        <td colspan="6">no records found</td>
    </tr>
{% endfor %}
</tbody>
</table>

 {% endif %}
{% endblock %}